insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Inception', 1970, 'NC-17', '120 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Dark Knight', 1980, 'PG', '180 minutes', 'Horror');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Pulp Fiction', 2008, 'G', '150 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Inception', 1982, 'R', '90 minutes', 'Sci-Fi');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Lord of the Rings: The Fellowship of the Ring', 1934, 'G', '180 minutes', 'Sci-Fi');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Inception', 1929, 'PG-13', '90 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Fight Club', 1960, 'PG-13', '90 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Forrest Gump', 1934, 'PG', '90 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Matrix', 1999, 'PG', '180 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Shawshank Redemption', 1981, 'NC-17', '90 minutes', 'Mystery');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Dark Knight', 1926, 'G', '120 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Lord of the Rings: The Fellowship of the Ring', 1965, 'PG', '180 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Shawshank Redemption', 2000, 'PG-13', '120 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Forrest Gump', 1920, 'PG', '90 minutes', 'Mystery');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Goodfellas', 1986, 'PG-13', '120 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Goodfellas', 1973, 'R', '180 minutes', 'Drama');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Fight Club', 1962, 'NC-17', '120 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Goodfellas', 1921, 'G', '150 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Lord of the Rings: The Fellowship of the Ring', 1949, 'R', '180 minutes', 'Action');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Godfather', 1995, 'NC-17', '180 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Matrix', 2015, 'PG-13', '150 minutes', 'Mystery');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Fight Club', 2012, 'R', '120 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Fight Club', 1980, 'PG', '90 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Dark Knight', 1950, 'G', '120 minutes', 'Action');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Fight Club', 1942, 'PG-13', '150 minutes', 'Sci-Fi');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Fight Club', 1975, 'PG-13', '90 minutes', 'Sci-Fi');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Fight Club', 1936, 'NC-17', '90 minutes', 'Horror');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Dark Knight', 1964, 'PG-13', '150 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Lord of the Rings: The Fellowship of the Ring', 1990, 'R', '120 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Shawshank Redemption', 1939, 'G', '120 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Dark Knight', 2014, 'NC-17', '120 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Goodfellas', 2017, 'G', '150 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Inception', 1967, 'NC-17', '120 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Forrest Gump', 1939, 'NC-17', '90 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Forrest Gump', 1945, 'NC-17', '150 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Lord of the Rings: The Fellowship of the Ring', 1932, 'R', '180 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Inception', 1921, 'NC-17', '180 minutes', 'Action');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Pulp Fiction', 1957, 'PG', '90 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Dark Knight', 1993, 'G', '90 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Shawshank Redemption', 1927, 'NC-17', '120 minutes', 'Comedy');
